### PR TITLE
Fix minor typo in docs

### PR DESCRIPTION
**Pull request by plq**

### CODE REVIEW

**Comment by plq** [comment]
I placed $FIXME$ marks where the meaning is not totally clear.

Nice project. I hope you like my work!

Cheers,

**Comment by plq** [comment]
btw, i'd `s/function/callable/g` in most places. not all callables are functions and not all functions are methods. You definitely don't want to say "method" here, but "function" is acceptable. However, I'd say "callable" instead of "function". It's totally  your call though.

**Comment by huseyinyilmaz** [comment]
First of all thank you for fixing up the documentation. I am not really good at writing documentation. It took me a lot more than writing the actual project. With your help, I would say, it became pretty decent if not complete. 

About function -> callable change, I agree with you. I did not really thought about it that deeply. I will go through the documentation again and do the change.

I will also go through the FIXME marks.

UPDATE: This commit should fix most of the problems. https://github.com/huseyinyilmaz/placebo/commit/8b0209789e6ba819531372c71d1a7d745d0aa2e8

**Comment by plq** [comment]
you are doing a fabulous job. keep up the good work.

:+1:

**Pull request merged**
